export default {
	products: [
		{ _id: "1", name: "Gold watch", category: "jelwelry", image: "/images/p1.jpg", price: "80", brand: "casio", rating: "4", numbReviews: 10 },
		{ _id: "2", name: "necklace", category: "Jewelry", image: "/images/p2.jpg", price: "60", brand: "fotzin", rating: "4", numbReviews: 9 },
		{ _id: "3", name: "chain", category: "jewelry", image: "/images/p3.jpg", price: "100", brand: "chinese", rating: "4", numbReviews: 7 },
		{
			_id: "4",
			name: " diamond ring",
			category: "pant",
			image: "/images/watch2.jpg",
			price: "100",
			brand: "Nike",
			rating: "4",
			numbReviews: 7,
		},
		{ _id: "5", name: "silver chain", category: "pant", image: "/images/watch3.jpg", price: "100", brand: "Abba", rating: "4", numbReviews: 7 },
		{
			_id: "6",
			name: "necklace",
			category: "pant",
			image: "/images/necklace.jpg",
			price: "100",
			brand: "Addidas",
			rating: "4",
			numbReviews: 7,
		},
		{ _id: "6", name: "ring", category: "pant", image: "/images/ring2.jpg", price: "100", brand: "Addidas", rating: "4", numbReviews: 7 },
		{
			_id: "7",
			name: "watch and rings",
			category: "pant",
			image: "/images/chains.jpg",
			price: "100",
			brand: "Addidas",
			rating: "4",
			numbReviews: 7,
		},
		{ _id: "8", name: "ear ring", category: "pant", image: "/images/earing2.jpg", price: "100", brand: "Addidas", rating: "4", numbReviews: 7 },
		{ _id: "9", name: "ear ring", category: "pant", image: "/images/earing.jpg", price: "100", brand: "Addidas", rating: "4", numbReviews: 7 },
		{
			_id: "10",
			name: "digital watch",
			category: "pant",
			image: "/images/watchDigital.jpg",
			price: "100",
			brand: "Addidas",
			rating: "4",
			numbReviews: 7,
		},
		{
			_id: "11",
			name: "silver watch",
			category: "pant",
			image: "/images/watchSilver.jpg",
			price: "100",
			brand: "Addidas",
			rating: "4",
			numbReviews: 7,
		},
		{
			_id: "12",
			name: "diamond ear ring",
			category: "pant",
			image: "/images/diamond.jpg",
			price: "100",
			brand: "Addidas",
			rating: "4",
			numbReviews: 7,
		},
		{
			_id: "13",
			name: "diamond ear ring",
			category: "pant",
			image: "/images/diamond2.jpg",
			price: "100",
			brand: "Addidas",
			rating: "4",
			numbReviews: 7,
		},
	],
};
